spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
mybatis-plus:
  mapper-locations: calsspath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000